services:
  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      MAVEN_USER_HOME: /box
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db
  db:
    image: mongo:8.0.13
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactive-flashcards
      MONGO_INITDB_ROOT_PASSWORD: reactive-flashcards
      MONGO_INITDB_DATABASE: reactive-flashcards
    ports:
      - "27017:27017"
  box:
    image: busybox
    volumes:
      - /box
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1025:25"
      - "1080:80"
volumes:
  db:
  box:
